server: 
  port: 9527
 
spring: 
  application:
    name: microservice-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservice-user
  prefix: /jbinfo
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservice-user
    mydept.path: /myuser/**
 
info:
  app.name: microservice-zuul
  company.name: www.jbinfo.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

