server: 
  port: 3344 
  
spring:
  application:
    name:  microservice-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:chenghuasui/microservice-config.git #GitHub上面的git仓库名字
 

